### ISSUE TITLE
Address issue found in routes/fb.js [Opened by bitHound]

### ISSUE THREAD

**Issue by wijagels** [Eaton-Software/messenger-home#5]
bitHound discovered 1 DuplicateFunction in [routes/fb.js](https://github.com/Eaton-Software/messenger-home/blob/91573e0e83f6f3ae7ffc226eb1a6b5de7300719f/routes/fb.js). For details go to [bitHound](https://www.bithound.io/github/Eaton-Software/messenger-home/blob/91573e0e83f6f3ae7ffc226eb1a6b5de7300719f/routes/fb.js). 

---

Tim fix your copy pasta

**Comment by AvocadosConstant** [comment]
Fixed by creating the sendMessage function
